#[derive(Hash, PartialEq, Eq, Debug, Copy, Clone)]
pub enum Category {
    Cache,
    Logs,
    RustTargets,
    NodeModules,
    PythonVenvs,
    PythonCaches,
    BunCache,
    GoCache,
    CargoGit,
    CargoRegistryCache,
    DiskImages,
    Gradle,
    GradleBuild,
    GradleCache,
    MavenTarget,
    M2Repository,
    PdmBuilds,
    NpmCache,
    ElectronCache,
    VscCache,
    #[cfg(target_os = "macos")]
    Xcode,
}
